# Generated by Django 4.1.7 on 2023-03-26 18:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Interface",
            fields=[
                (
                    "name",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("address", models.CharField(default="", max_length=100)),
                ("port", models.PositiveIntegerField(null=True)),
                (
                    "public_key",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("endpoint_ip_peer", models.GenericIPAddressField()),
                (
                    "allowed_ips_peer",
                    models.CharField(default="0.0.0.0/0", max_length=100),
                ),
                (
                    "status",
                    models.BooleanField(
                        choices=[(True, "active"), (False, "inactive")], default=False
                    ),
                ),
                (
                    "state",
                    models.BooleanField(
                        choices=[(True, "running"), (False, "dead")],
                        default=False,
                        editable=False,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="Peer",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("private_key", models.CharField(max_length=1000)),
                ("public_key", models.CharField(max_length=1000, unique=True)),
                ("allowed_ips", models.CharField(max_length=1000, unique=True)),
                (
                    "listen_port",
                    models.PositiveIntegerField(
                        default=51820,
                        validators=[django.core.validators.MaxValueValidator(65535)],
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        choices=[(True, "active"), (False, "inactive")], default=True
                    ),
                ),
                ("state", models.CharField(blank=True, max_length=1000)),
                ("description", models.CharField(blank=True, max_length=1000)),
                (
                    "interface",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wgconsole.interface",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
